# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'
use_frameworks!
target 'wallpaper' do
    pod 'UIActivityIndicator-for-SDWebImage'
    pod 'Toast-Swift', '~> 5.0.0'
end
